name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Start prop_test
      run: ./gradlew prop_test -Dappid=${{ secrets.APP_ID }}

    #скачиваем историю тестов
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    #генерируем отчёт
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    #публикуем отчёт
    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v2
      if: always()
      env:
        PERSONAL_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
